### ISSUE TITLE
Street Search Issues - New

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#29]
Sodom Road North Canaan - Finds a location but places the map somewhere in a field. The representative point is somewhere to the north (off the road).

Trescott Hill Road North Canaan - Does a similar thing to the issue above

The attached PPT also highlights another issue with addresses that border MA.

[North Canaan tickets.pptx](https://github.com/polysteve/MobileLocater/files/69913/North.Canaan.tickets.pptx)

**Comment by 3DXScape** [comment]
This looked very similar to the problem with selecting the Whitney Ave/State Hwy 15 NB in Hamden choice off the list of suggestion.  I traced through the process to see what is being passed back and forth and it looks like it is the same issue.
Still investigating - trying to determine where the process goes bad.

**Comment by 3DXScape** [comment]
These seem to be due to a Pelican application limit to moving close to the state line. It appears that the correct location for Sodom Rd, for example, is just above and to the left of the map returned but it is not possible at zoom level 18. To see that the target is in the right place, search for Sodom Rd North Canaan and then click three times on the "-" at the bottom of the map scale controller to zoom out to level 15. You will then see the target centered on Sodom Rd.
