### ISSUE TITLE
STONINGTON

### ISSUE THREAD

**Issue by HelloMrWillemain** [3DXScape/MobileLocater#70]
On staging site, town of Stonington looks to have difficulties deriving intersections. Searches for streets that are not intersections, it finds an area around them as the location. 

![image](https://cloud.githubusercontent.com/assets/17441865/16849620/51a56bfc-49c9-11e6-8451-aea6e87b81f7.png)
![image](https://cloud.githubusercontent.com/assets/17441865/16849634/6644f32a-49c9-11e6-9a1b-15b8753b02e2.png)
![image](https://cloud.githubusercontent.com/assets/17441865/16849670/90760292-49c9-11e6-8b24-2faff618e0f0.png)

**Comment by 3DXScape** [comment]
We'll take a look at this but I suspect that this is the plan in order to position the may in the correct general area when the description is "almost OK". You don't get any indication that the intersection is off but you _do_ get to see the part of the map that would let you select a correct (according to the map at least) intersection.
